#!/usr/bin/env python3
"""
Checks allocation.html against portfolio_model.py. Exits non-zero on any mismatch.

The page is generated by build.py. This file deliberately does NOT import it for
its content checks: every figure is re-derived here from the model with its own
arithmetic and formatting, so a bug in the generator is caught rather than copied.
One check does import it -- the page must be byte-for-byte what build.py writes
today, so a page left stale after a model change fails.

Sections: 1 model self-consistency · 2 model inputs · 3 model analytics ·
4 freshness · 5 page structure · 6 page content, pane by pane · 7 hygiene.
"""
import re, sys, math
import portfolio_model as M

html = open('allocation.html').read()
fails, checks = [], 0

def ck(label, ok, got=None, want=None):
    global checks
    checks += 1
    if not ok:
        fails.append(f'{label}: page={got!r} model={want!r}')

def present(label, needle, hay=None):
    ck(label, needle in (html if hay is None else hay), needle[:80], 'present')

MINUS = '−'
def hu(x, dp=2):   return f'{M.r2h(x, dp):.{dp}f}'
def neg(x, dp=1):  return MINUS + hu(abs(x), dp)
def sgn(x, dp=2):
    v = M.r2h(x, dp)
    return ('+' if v > 0 else MINUS if v < 0 else '±') + f'{abs(v):.{dp}f}'
_MONTHS = 'January February March April May June July August September October November December'.split()
def day(iso, short=True):
    m = _MONTHS[int(iso[5:7]) - 1]
    return f'{int(iso[8:])} {m[:3] if short else m}'
def pane(pid):
    i = html.index(f'id="{pid}"'); j = html.find('<section', i + 1)
    return html[i:j if j > 0 else html.index('<nav class="tabs"')]

E = M.export()
B, O = M.PORTFOLIOS['baseline'], M.PORTFOLIOS['optimized']
ST = {n: {r: M.stats(w, r) for r in M.REGIME} for n, w in M.PORTFOLIOS.items()}

# ══ 1 · model self-consistency, independent of the page ═══════════════════════
for pname, w in M.PORTFOLIOS.items():
    ck(f'{pname} weights sum to 100', sum(w.values()) == 100, sum(w.values()), 100)
    ck(f'{pname} weights end in 5 or 0', all(v % 5 == 0 for v in w.values()), w, 'multiples of 5')
    ck(f'{pname} holds all four', set(w) == {'QQQ', 'IEMG', 'SGOV', 'BMNR'} and min(w.values()) >= 5, w, 'all four, 5%+')
    ck(f'{pname} BMNR capped at 5%', w['BMNR'] == 5, w['BMNR'], 5)
    for reg in M.REGIME:
        st = ST[pname][reg]
        ck(f'{pname}/{reg} risk contributions sum to 100', abs(sum(st['rc'].values()) - 100) < 1e-6, sum(st['rc'].values()), 100)
        ck(f'{pname}/{reg} sigma inside sleeve bounds',
           min(M.REGIME[reg]['vol'].values()) < st['vol'] < max(M.REGIME[reg]['vol'].values()), st['vol'], 'bounded')
        ck(f'{pname}/{reg} VaR worsens with horizon', st['var'][0.25] > st['var'][0.5] > st['var'][1.0], st['var'], 'monotone')
    ck(f'{pname} normalized sigma exceeds calm', ST[pname]['normalized']['vol'] > ST[pname]['calm']['vol'], '', 'norm > calm')
for k, c in E['components'].items():
    ck(f'{k} components sum to gross', abs(c['div'] + c['eps'] + c['val'] + c['fx'] - c['gross']) < 0.005, c, 'sums')
    ck(f'{k} gross minus fee equals net', abs(c['gross'] - c['er'] - c['net']) < 0.005, c, 'nets')
    ck(f'{k} valuation term is the annualised move to its own 10-yr mean',
       abs(c['val'] - M.r2h(M.annualised(M.OBS[k]['fwd_pe'], M.OBS[k]['pe_end']))) < 1e-9, c['val'], M.OBS[k]['fwd_pe'])
b_ = M.A['BMNR']
ck('BMNR components sum to net', abs(b_['eth'] + b_['stake'] + b_['mnav'] + b_['drag'] - b_['net']) < 0.005, b_, 'sums')
ck('driver weights sum to 1', abs(sum(x for _, _, x in M.DRIVERS) - 1) < 1e-9)
ck('gauge rescale commutes', abs(E['gauge']['score5'] - round(M.to5(E['gauge']['score10']), 4)) < 1e-9)
for k, v in E['regions'].items():
    ck(f'{k} mean matches its scores', abs(sum(M.to5(x) for x in M.REGIONS[k]) / 4 - v['mean']) < 0.05, v['mean'], 'mean')
ck('optimized drawdown beats baseline in both regimes',
   all(ST['optimized'][r]['dd'] < ST['baseline'][r]['dd'] for r in M.REGIME), '', 'optimized lower')

# ══ 2 · model inputs: derived where they can be, reconciled where they cannot ══
for k, pr in M.PRICES.items():
    ck(f'{k} dividend yield derives from its price',
       abs(M.OBS[k]['div'] - M.r2h(pr['ttm_div'] / pr['px'] * 100)) < 1e-9, M.OBS[k]['div'], pr['ttm_div'] / pr['px'] * 100)
    ck(f'{k} forward P/E derives from the same price',
       abs(M.OBS[k]['fwd_pe'] - pr['basis_fwd'] * pr['px'] / pr['basis_px']) < 5e-3, M.OBS[k]['fwd_pe'], 'basis x price move')
H = M.BMNR_HOLDINGS
ck('BMNR staked share matches its token counts', abs(M.BMNR['stake_share'] - H['staked'] / H['held']) < 0.0005,
   M.BMNR['stake_share'], round(H['staked'] / H['held'], 4))
ck('BMNR mNAV is market cap over crypto', abs(M.BMNR['mnav'] - round(M.BMNR_MCAP_B / H['crypto_b'], 2)) < 1e-9,
   M.BMNR['mnav'], M.BMNR_MCAP_B / H['crypto_b'])
ck('BMNR ETH value reconciles with the release', abs(H['held'] * H['eth_px'] / 1e9 - H['crypto_b']) < 0.1,
   H['held'] * H['eth_px'] / 1e9, H['crypto_b'])
ck('SGOV assumption is the policy midpoint', abs(M.SGOV_GROSS - sum(M.FED_RANGE) / 2) < 1e-9, M.SGOV_GROSS, sum(M.FED_RANGE) / 2)
ck('SGOV is the lowest-return sleeve', M.A['SGOV']['net'] == min(a['net'] for a in M.A.values()), M.A['SGOV']['net'], 'lowest')
ser = dict(M.VIX_SERIES); vals = [v for _, v in M.VIX_SERIES]
ck('VIX spot is the last close in the series', M.VIX_SPOT == M.VIX_SERIES[-1][1], M.VIX_SPOT, M.VIX_SERIES[-1])
ck('VIX series dated in order, no duplicates', [d for d, _ in M.VIX_SERIES] == sorted(set(ser)), list(ser), 'ascending, unique')
for (d0, a), (d1, b) in zip(M.VIX_SERIES, M.VIX_SERIES[1:]):
    ck(f'VIX move {d0} to {d1} plausible', abs(b - a) / a < 0.25, f'{(b - a) / a * 100:+.1f}%', '< 25%')
ck('2026 VIX low sits below every close on file', M.VIX_2026['low'] < min(vals), M.VIX_2026['low'], min(vals))
ck('the decision day is in the series', M.FOMC_DATE in ser, M.FOMC_DATE, 'in series')
ck('masthead date is the last VIX close', M.MARKET['asof'] == M.VIX_ASOF, M.MARKET['asof'], M.VIX_ASOF)
ck('previous close is the low of the series', M.VIX_SERIES[-2][1] == min(vals), M.VIX_SERIES[-2][1], min(vals))

# ══ 3 · model analytics ════════════════════════════════════════════════════════
cal = [r for _, r in M.cal_line()]; cal0 = [r for _, r in M.cal_line(cash_vol=0.0)]
ck('CAL ratio is exact with riskless cash', max(cal0) - min(cal0) < 1e-12, max(cal0) - min(cal0), '< 1e-12')
ck('CAL ratio is constant to within SGOV vol', max(cal) - min(cal) < 1e-4, max(cal) - min(cal), '< 1e-4')
ck('CAL uses the recommended risky mix', M.risky_mix() == (O['QQQ'], O['IEMG'], O['BMNR']), M.risky_mix(), 'optimized')
EFF, N_ADM = M.efficient()
ck('frontier fits its own axes', all(M.FR_X[0] <= d <= M.FR_X[1] and M.FR_Y[0] <= c <= M.FR_Y[1] for d, c, _ in EFF))
BEST = M.best_sharpe('calm')
ck('best-Sharpe book survives an unrestricted search', BEST == M.frontier('calm', sgov_min=5)[0][0], BEST, 'same as BMNR-pinned')
ctx = M.base_ctx()
for p, w in M.PORTFOLIOS.items():
    for r in M.REGIME:
        a, b = ST[p][r], M.stats_n(w, r, ctx)
        ck(f'stats_n reproduces stats: {p}/{r}', all(abs(a[k] - b[k]) < 1e-12 for k in ('cagr', 'fee', 'vol', 'dd', 'naive', 'sharpe'))
           and all(abs(a['rc'][k] - b['rc'][k]) < 1e-9 for k in w))
ck('stress lift matches the published regimes', abs(M.stress_lift() - 0.17) < 5e-3, M.stress_lift(), 0.17)
cand = M.with_candidate('TEST', 8.0, 0.30, 22.0, 50.0, {('QQQ', 'TEST'): 0.50, ('IEMG', 'TEST'): 0.45, ('BMNR', 'TEST'): 0.30})
ck('a candidate sleeve is stressed like every other pair',
   all(cand['regime']['normalized']['rho'][p] > cand['regime']['calm']['rho'][p] for p in (('QQQ', 'TEST'), ('IEMG', 'TEST'), ('BMNR', 'TEST'))))
ck('a candidate leaves the four sleeves untouched',
   all(cand['regime'][r]['vol'][k] == M.REGIME[r]['vol'][k] for r in M.REGIME for k in M.DD))
SENS, o0, g0 = M.sensitivity()
for lab, _now, key, val in M.SENS:
    tk, fld = key.split('_', 1)
    cur = M.OBS[tk][fld] if tk in M.OBS else M.BMNR[fld] if tk == 'BMNR' else M.SGOV_GROSS
    ck(f'sensitivity step is one unit: {lab}', abs(abs(val - cur) - 1) < 1e-9, abs(val - cur), 1)
ck('sensitivity ordered by effect', SENS == sorted(SENS, key=lambda r: -abs(r['d_cagr'])))
ck('sensitivity baseline reproduces the model', abs(o0 - ST['optimized']['calm']['cagr']) < 1e-9, o0, 'same')
ck('BMNR inputs cannot move the choice', all(abs(r['d_gap']) < 5e-4 for r in SENS if r['label'].startswith('BMNR')))
CALB = M.calibration(B, O); SEP, SEP_N = M.separable()
ck('comparison error is smaller than level error', CALB['se'] < M.se_level('optimized'), CALB['se'], M.se_level('optimized'))
MINE, JPM = M.scenario({k: M.A[k]['net'] for k in M.A}), M.scenario(M.alt_nets())
ck('scenario reproduces the model on its own inputs', abs(MINE['rows']['optimized']['cagr'] - ST['optimized']['calm']['cagr']) < 1e-9)
ck("J.P. Morgan inputs raise the best book's EM weight", JPM['best_w']['IEMG'] > MINE['best_w']['IEMG'], (MINE['best_w'], JPM['best_w']))

# ══ 4 · freshness: the page is exactly what the generator writes today ════════
import build
ck('page is exactly what build.py writes from the current model', build.render() == html, 'stale page', 'run python3 build.py')

# ══ 5 · page structure ════════════════════════════════════════════════════════
for tag in ('section', 'div', 'table', 'article', 'svg', 'nav', 'script', 'style', 'p', 'tr', 'td', 'th', 'span', 'button', 'a', 'text', 'g'):
    o = len(re.findall(r'<%s[\s/>]' % tag, html)); c = len(re.findall(r'</%s>' % tag, html))
    ck(f'tags <{tag}> balanced', o == c, o, c)
ids = re.findall(r'\bid="([^"]+)"', html)
ck('ids are unique', len(ids) == len(set(ids)), len(ids), len(set(ids)))
panes = re.findall(r'<section class="pane[^"]*" id="([^"]+)" role="tabpanel"', html)
ck('five panes, one per tab', sorted(panes) == sorted(re.findall(r'data-p="([^"]+)"', html)) and len(panes) == 5, panes)
ck('exactly one pane starts visible', html.count('class="pane on"') == 1)
revs = re.findall(r'<span>Rev\. (\d+) ·', html)
ck('one revision stamp, the current one', revs == [str(M.REVISION)], revs, M.REVISION)

# ══ 6 · page content, re-derived ══════════════════════════════════════════════
MK = M.MARKET; SPOT, PREV = M.VIX_SPOT, M.VIX_SERIES[-2][1]
FQ, FI = M.OBS['QQQ']['fwd_pe'], M.OBS['IEMG']['fwd_pe']
bc, oc, bn, on = ST['baseline']['calm'], ST['optimized']['calm'], ST['baseline']['normalized'], ST['optimized']['normalized']

# masthead
present('masthead', f'<span>As of {day(MK["asof"])} {MK["asof"][:4]}</span><span>10-yr horizon</span>'
        f'<span>Fed {M.FED_RANGE[0]:.2f}–{M.FED_RANGE[1]:.2f}%</span><span>VIX {SPOT:.2f}</span>'
        f'<span>Brent ${MK["brent"]:.2f}</span><span>UST 10y {MK["ust10"]:.2f}%</span><span>Rev. {M.REVISION} · re-verified</span>')

# macro
P = pane('p-macro')
chg = (SPOT / PREV - 1) * 100
present('lead: 10-year move', f'sent the 10-year {"up" if MK["ust10_chg_bp"] > 0 else "down"} {abs(MK["ust10_chg_bp"])}bp to <b>{MK["ust10"]:.2f}%</b>', P)
present('lead: Brent move', f'Brent settled {"up" if MK["brent_chg_pct"] > 0 else "down"} {hu(abs(MK["brent_chg_pct"]))}% at <b>${MK["brent"]:.2f}</b>', P)
present('lead: VIX move', f'the VIX {"rose" if chg > 0 else "fell"} {hu(abs(chg), 1)}% to <b>{SPOT:.2f}</b>', P)
g = E['gauge']
present('gauge value', f'<div class="gauge-val">{g["display"]}<small>/5</small></div>', P)
present('gauge arc', f'stroke-dasharray="{g["arc_dash"]} 251.4"', P)
present('gauge needle', f'x2="{g["needle"][0]}" y2="{g["needle"][1]}"', P)
ck('gauge is on a 1-5 scale', 1 <= g['score5'] <= 5 and '/10' not in P, g['score5'], '1-5')
for (name, s10, wt), (_, s5, fl) in zip(M.DRIVERS, g['drivers']):
    ck(f'driver {name}: weight, score and bar',
       re.search(r'%s <span class="wt">w %d%%</span></div><div class="drv-s"[^>]*>%s</div>\s*<div class="drv-bar"><i style="width:%s%%;'
                 % (re.escape(name.replace('&', '&amp;')), round(wt * 100), s5, fl), P) is not None, name, (s5, fl))
present('valuation driver multiples', f'Nasdaq-100 at {hu(FQ, 1)}× forward vs EM at {hu(FI, 1)}× — a {hu((1 - FI / FQ) * 100, 0)}% discount', P)
present('valuation driver VIX discount', f'The VIX at {SPOT:.2f} sits {hu((1 - SPOT / M.VIX_MEAN) * 100, 0)}% below its {M.VIX_MEAN} long-run mean', P)
present('policy driver range', f'the range is {M.FED_RANGE[0]:.2f}–{M.FED_RANGE[1]:.2f}%', P)
for t in ('SGOV', 'QQQ', 'IEMG', 'BMNR'):
    present(f'transmission row for {t}', f'<div class="tick" style="background:var(--{t.lower()})">{t}</div>', P)
present('SGOV transmission figures', f'The {M.SGOV_GROSS:g}% policy midpoint nets {M.A["SGOV"]["net"]:.2f}%', P)
present('QQQ transmission figures', f'at {hu(FQ, 1)}× forward — {"above" if FQ > M.OBS["QQQ"]["pe_end"] else "below"} its {M.OBS["QQQ"]["pe_end"]}× average', P)
present('IEMG transmission figures', f'The cheapest bloc at {hu(FI, 1)}×, {"below" if FI < M.OBS["IEMG"]["pe_end"] else "above"} its {M.OBS["IEMG"]["pe_end"]}× average', P)
present('BMNR transmission correlation', f'a {M.REGIME["calm"]["rho"][("QQQ", "BMNR")]:.2f} correlation to QQQ', P)

# regions
P = pane('p-regions')
names = {'Asia / EM': 'Asia / Emerging', 'United States': 'United States', 'Europe': 'Europe'}
by_mean = sorted(E['regions'], key=lambda k: -E['regions'][k]['mean'])
badges = re.findall(r'<span class="nm">([^<]+)</span><span class="rank[^"]*">Rank (\d)</span>', P)
ck('rank badges follow mean scores', badges == [(names[k], str(i + 1)) for i, k in enumerate(by_mean)], badges, by_mean)
ck('region scores on the bars', [float(x) for x in re.findall(r'hz-v">([\d.]+)<', P)] == sum((E['regions'][k]['scores'] for k in by_mean), []))
ck('region bar fills', [float(x) for x in re.findall(r'hz-t"><i style="width:([\d.]+)%', P)] == sum((E['regions'][k]['fills'] for k in by_mean), []))
ck('every bloc scored at four horizons', all(P.count(f'<span class="hz-l">{h}</span>') == 3 for h in ('3 mo', '6 mo', '12 mo', '10 yr')))
for k, v in E['regions'].items():
    m = re.search(r'<td>%s</td>((?:<td class="n">[\d.]+</td>)+)' % re.escape(k), P)
    ck(f'matrix row {k}', m is not None and [float(x) for x in re.findall(r'([\d.]+)', m.group(1))] == v['scores'] + [v['mean']], k)
top, sec = by_mean[0], by_mean[1]
present('ranking lead stated', f'{names[top]} leads by {M.r2h(E["regions"][top]["scores"][0] - E["regions"][sec]["scores"][0], 1):.1f} at 3 months and '
        f'{M.r2h(E["regions"][top]["scores"][3] - E["regions"][sec]["scores"][3], 1):.1f} at 10 years', P)
present('EM multiple in the Asia note', f'Equities at {hu(FI, 1)}× forward', P)

# volatility
P = pane('p-vol')
present('VIX hero', f'<div class="k">VIX, {day(M.VIX_ASOF)}</div><div class="v">{SPOT:.2f}</div>', P)
present('2026 range hero', f'<div class="v">{M.VIX_2026["low"]:.2f} · {M.VIX_2026["high"]:.2f}</div>', P)
present('VIX discount and dates', f'Spot is {hu((1 - SPOT / M.VIX_MEAN) * 100, 1)}% below the 2016–2023 mean of {M.VIX_MEAN}. '
        f'The 2026 low was {day(M.VIX_2026["low_date"], False)}; the high {day(M.VIX_2026["high_date"], False)}.', P)
for lab, h in (('1 day', 1 / 252), ('3 months', 0.25), ('6 months', 0.5), ('12 months', 1.0)):
    sig = M.r2h(SPOT * math.sqrt(h))                 # displayed sigma; the band is 1.645 x what is shown
    dp = 2 if h < 0.1 else 1
    present(f'term row {lab}', f'<tr><td>{lab}</td><td class="n">{math.sqrt(h):.3f}</td><td class="n">{sig:.2f}%</td>'
            f'<td class="n">±{hu(1.645 * sig, dp)}%</td></tr>', P)
for lab, h in (('3 months', 0.25), ('6 months', 0.5), ('12 months', 1.0)):
    present(f'VaR row {lab}', f'<tr><td>{lab}</td><td class="n">{bc["vol"] * h ** 0.5:.2f}%</td><td class="n neg">{neg(bc["var"][h])}%</td>'
            f'<td class="n">{oc["vol"] * h ** 0.5:.2f}%</td><td class="n neg">{neg(oc["var"][h])}%</td></tr>', P)
present('10-yr max DD row', f'<td>10 yr max DD</td><td class="n" colspan="2">{neg(bc["dd"])}%</td><td class="n" colspan="2">{neg(oc["dd"])}%</td>', P)
present('normalized VaR row', f'<td>12 mo, normalized</td><td class="n">{bn["vol"]:.2f}%</td><td class="n neg">{neg(bn["var"][1.0])}%</td>'
        f'<td class="n">{on["vol"]:.2f}%</td><td class="n neg">{neg(on["var"][1.0])}%</td>', P)
present('normalized max DD row', f'<td>Max DD, normalized</td><td class="n neg" colspan="2">{neg(bn["dd"])}%</td><td class="n neg" colspan="2">{neg(on["dd"])}%</td>', P)
for k in ('QQQ', 'IEMG', 'SGOV', 'BMNR'):
    d = 0 if k == 'BMNR' else 1
    ck(f'two-regime row {k}', re.search(r'<tr><td>%s</td><td class="n">%s%%</td><td class="n[^"]*">%s%%</td></tr>'
       % (k, f'{M.REGIME["calm"]["vol"][k]:.{d}f}', f'{M.REGIME["normalized"]["vol"][k]:.{d}f}'), P) is not None, k)
for a, b in (('QQQ', 'IEMG'), ('QQQ', 'BMNR'), ('IEMG', 'BMNR')):
    present(f'correlation row {a}·{b}', f'<td>ρ {a}·{b}</td><td class="n">{M.REGIME["calm"]["rho"][(a, b)]:.2f}</td>'
            f'<td class="n neg">{M.REGIME["normalized"]["rho"][(a, b)]:.2f}</td>', P)
present('uplift and regime drawdowns', f'Volatility mean-reverted to {M.VIX_MEAN} (×{hu(M.UPLIFT)}) and crisis correlations turn the optimized book&#8217;s '
        f'{neg(oc["dd"])}% drawdown into {neg(on["dd"])}%', P)
rcard = P[P.index('Risk contribution'):P.index('Ten-year view')]
for k in ('QQQ', 'IEMG', 'SGOV', 'BMNR'):
    x = on['rc'][k]
    ck(f'risk card {k}', re.search(r'%s <span class="wt">%d%% weight</span></div><div class="drv-s">%.1f%%</div>\s*'
       r'<div class="drv-bar"><i style="width:%.1f%%;' % (k, O[k], x, max(x, 1)), rcard) is not None, k, f'{x:.1f}%')
present('BMNR risk-to-weight', f'BMNR is {O["BMNR"]}% of capital but {on["rc"]["BMNR"]:.1f}% of risk ({hu(on["rc"]["BMNR"] / O["BMNR"], 1)}×)', P)
for k in ('QQQ', 'IEMG'):
    lo_, hi_ = M.REGIME['calm']['vol'][k] * M.DD_MULT, M.REGIME['normalized']['vol'][k] * M.DD_MULT
    word = 'sits between' if lo_ <= M.DD[k] <= hi_ else 'sits beyond both' if M.DD[k] > hi_ else 'sits inside both'
    present(f'{k} sleeve drawdown against the sigma model', f'{k} {neg(M.DD[k], 0)}% {word}', P)
    present(f'{k} sigma-model readings', f'({neg(lo_)}%, {neg(hi_)}%)', P)

# sleeves
P = pane('p-assets')
slides = dict(re.findall(r'<div class="sl-tick">(\w+)</div>(.*?)</article>', P, re.S))
ck('four slides, one per holding', sorted(slides) == ['BMNR', 'IEMG', 'QQQ', 'SGOV'], sorted(slides))
for k, sl in slides.items():
    a = M.A[k]
    present(f'{k} slide net CAGR', f'<div class="k">Net 10-yr CAGR</div><div class="v" style="color:var(--pos)">{a["net"]:.2f}%</div>', sl)
    present(f'{k} slide expected drawdown', f'<div class="k">Expected max DD</div><div class="v" style="color:var(--neg)">{neg(M.DD[k], 0 if M.DD[k] >= 1 else 1)}%</div>', sl)
    present(f'{k} slide terminal', f'$10,000 → 10 yr</span><span class="v">${round(10000 * (1 + a["net"] / 100) ** 10):,}</span>', sl)
    m = re.search(r'<div class="k">Baseline</div><div class="v">(\d+)%</div></div><div><div class="k">Optimized</div><div class="v"[^>]*>(\d+)%', sl)
    ck(f'{k} slide weights', m is not None and (int(m.group(1)), int(m.group(2))) == (B[k], O[k]), m and m.groups(), (B[k], O[k]))
    if k != 'BMNR':
        present(f'{k} slide gross', f'Gross forecast</span><span class="v">{hu(a["gross"])}%', sl)
        present(f'{k} slide expense ratio', f'Expense ratio</span><span class="v">{a["er"]:.2f}%', sl)
        ck(f'{k} net is gross minus the fee shown', abs(M.r2h(a['gross']) - a['er'] - a['net']) < 0.006, (a['gross'], a['er'], a['net']))
for k in ('QQQ', 'IEMG'):
    pr = M.PRICES[k]
    present(f'{k} slide price and date', f'Price ({day(pr["px_asof"])})</span><span class="v">${pr["px"]:.2f}', slides[k])
    present(f'{k} slide forward P/E', f'Forward P/E</span><span class="v">{hu(M.OBS[k]["fwd_pe"], 1)}×', slides[k])
    present(f'{k} slide dividend yield', f'Dividend yield</span><span class="v">{M.OBS[k]["div"]:.2f}%', slides[k])
q, i = M.A['QQQ'], M.A['IEMG']
present('QQQ role: valuation direction', f'{"above" if FQ > M.OBS["QQQ"]["pe_end"] else "below"} its own {M.OBS["QQQ"]["pe_end"]}× average, the multiple '
        f'{"costs" if q["val"] < 0 else "adds"} {hu(abs(q["val"]))}%/yr', slides['QQQ'])
rv = {k: (M.A[k]['net'] - M.A['SGOV']['net']) / M.REGIME['calm']['vol'][k] for k in ('QQQ', 'IEMG')}
rel = 'level with' if abs(rv['QQQ'] - rv['IEMG']) < 0.01 else ('ahead of' if rv['IEMG'] > rv['QQQ'] else 'behind')
present('IEMG role: valuation and risk-adjusted relation', f'the multiple {"adds" if i["val"] > 0 else "costs"} {hu(abs(i["val"]))}%/yr; currency costs '
        f'{hu(abs(i["fx"]))}%/yr. {rel[0].upper() + rel[1:]} QQQ on return per unit of risk', slides['IEMG'])
present('BMNR slide price', f'Price ({day(H["px_asof"])})</span><span class="v">${H["px"]:.2f}', slides['BMNR'])
present('BMNR slide market cap', f'Market cap</span><span class="v">${H["px"] * H["shares_m"] / 1000:.2f}B', slides['BMNR'])
present('BMNR slide treasury', f'ETH treasury</span><span class="v">{H["held"]:,}', slides['BMNR'])
present('BMNR slide staked share', f'ETH staked</span><span class="v">{H["staked"] / H["held"] * 100:.1f}%', slides['BMNR'])
present('BMNR slide mNAV', f'{H["px"] * H["shares_m"] / 1000 / H["total_b"]:.2f}× / {M.BMNR["mnav"]:.2f}×', slides['BMNR'])
present('BMNR slide build-up', f'{b_["eth"]:.1f}% ETH appreciation {sgn(b_["stake"])}% staking {sgn(b_["mnav"])}% premium normalisation '
        f'{sgn(b_["drag"])}% dilution drag = {b_["net"]:.2f}%', slides['BMNR'])

# portfolios
P = pane('p-port')
C = 2 * math.pi * 64
for name, segs in E['donuts'].items():
    ck(f'donut {name} closes', abs(sum(s[1] for s in segs) - C) < 0.02)
    for tk, seg, gap, off in segs:
        present(f'donut {name} {tk}', f'stroke-dasharray="{seg:.2f} {gap:.2f}" stroke-dashoffset="{off:.2f}"'.replace('-0.00', '0'), P)
    present(f'donut {name} centre', f'font-weight="600">{ST[name]["calm"]["cagr_d"]:.2f}</text>', P)
    for tk, pct in M.PORTFOLIOS[name].items():
        present(f'{name} legend {tk}', f'{tk}<em>{pct}%</em>', P)
d = {k: O[k] - B[k] for k in B}
present('the shift between the books', ' and '.join(f'{-d[k]} points out of {k}' for k in d if d[k] < 0) + ' — ' +
        ', '.join(f"{d[k]} to {'the reserve' if k == 'SGOV' else k}" for k in d if d[k] > 0), P)
def row(label):
    m = re.search(r'<td>%s</td>((?:<td class="n[^"]*">[^<]*</td>)+)</tr>' % re.escape(label), P)
    return re.findall(r'<td class="n[^"]*">([^<]*)</td>', m.group(1)) if m else None
def dd(a, b, p): return sgn(M.r2h(b, p) - M.r2h(a, p), p)
def usd(x): return ('+' if x > 0 else MINUS if x < 0 else '') + f'${abs(x):,.0f}'
cmp = {
  'Net 10-yr CAGR': [f'{bc["cagr_d"]:.2f}%', f'{oc["cagr_d"]:.2f}%', dd(bc['cagr_d'], oc['cagr_d'], 2)],
  'Weighted fee': [f'{bc["fee"]:.3f}%', f'{oc["fee"]:.3f}%', dd(bc['fee'], oc['fee'], 3)],
  'σ — calm (today)': [f'{bc["vol"]:.2f}%', f'{oc["vol"]:.2f}%', dd(bc['vol'], oc['vol'], 2)],
  'σ — vol normalized': [f'{bn["vol"]:.2f}%', f'{on["vol"]:.2f}%', dd(bn['vol'], on['vol'], 2)],
  'Max DD — calm': [f'{neg(bc["dd"])}%', f'{neg(oc["dd"])}%', dd(oc['dd'], bc['dd'], 1)],
  'Max DD — normalized': [f'{neg(bn["dd"])}%', f'{neg(on["dd"])}%', dd(on['dd'], bn['dd'], 1)],
  'Correlated-stress DD': [f'{neg(bc["naive"])}%', f'{neg(oc["naive"])}%', dd(oc['naive'], bc['naive'], 1)],
  'Return / risk (calm)': [f'{bc["sharpe"]:.3f}', f'{oc["sharpe"]:.3f}', dd(bc['sharpe'], oc['sharpe'], 3)],
  '$10,000 → 10 yr': [f'${bc["terminal"]:,.0f}', f'${oc["terminal"]:,.0f}', usd(M.r2h(oc['terminal'], 0) - M.r2h(bc['terminal'], 0))],
  '10-yr fee drag': [f'{MINUS}${bc["fee_drag"]:,.0f}', f'{MINUS}${oc["fee_drag"]:,.0f}', usd(M.r2h(bc['fee_drag'], 0) - M.r2h(oc['fee_drag'], 0))],
}
for lab, want in cmp.items():
    ck(f'comparison row {lab}', row(lab) == want, row(lab), want)
gap = M.r2h(M.r2h(bc['cagr_d']) - M.r2h(oc['cagr_d']))
cut = M.r2h(M.r2h(bn['dd'], 1) - M.r2h(on['dd'], 1), 1)
present('the trade, stated', f'gives up {gap:.2f} points of CAGR to cut the normalized drawdown by {cut:.1f} points, '
        f'at almost the same return per unit of risk ({oc["sharpe"]:.3f} vs {bc["sharpe"]:.3f})', P)
fmt_cell = lambda x, s: '—' if abs(x) < 5e-3 else (sgn(x) if s else hu(x))
for lab, fld, s in (('Dividend yield', 'div', True), ('Earnings growth', 'eps', True), ('Valuation change', 'val', True),
                    ('Currency drag', 'fx', True), ('Gross CAGR', 'gross', False), ('Net CAGR', 'net', False)):
    want = [fmt_cell(M.A[k][fld], s) for k in ('QQQ', 'IEMG')]
    ck(f'building block {lab}', row(lab) == want, row(lab), want)
ck('building block Expense ratio', row('Expense ratio') == [f'{MINUS}{M.A[k]["er"]:.2f}' for k in ('QQQ', 'IEMG')], row('Expense ratio'))
present('terminal multiples stated', f'NDX {M.OBS["QQQ"]["pe_end"]}×, MSCI EM {M.OBS["IEMG"]["pe_end"]}×', P)
present('frontier chart', M.frontier_svg(), P)
ON = {n: any(w == M.PORTFOLIOS[n] for _, _, w in EFF) for n in M.PORTFOLIOS}
dom = [(dd_, dc_, w) for dd_, dc_, w in ((M.stats(w, 'normalized')['dd'], M.stats(w, 'normalized')['cagr'], w) for w in M.admissible(5))
       if dd_ <= bn['dd'] and dc_ >= bn['cagr'] and (dd_ < bn['dd'] or dc_ > bn['cagr'])]
ck('frontier call-out matches the efficiency test',
   ('The recommended book is efficient; the baseline, by a hair, is not.' in P) == (ON['optimized'] and not ON['baseline'] and len(dom) == 1), ON)
if len(dom) == 1:
    dd_, dc_, dw = dom[0]
    present('the book that beats the baseline, and by how much',
            f'by +{hu(dc_ - bn["cagr"])} points of CAGR and {hu(bn["dd"] - dd_, 1)} of drawdown', P)
    present('admissible count', f'Across all {N_ADM} allocations with BMNR at 5%', P)
present('efficient count', f'{len(EFF)} allocations are efficient', P)
se = M.se_level('optimized'); lo95, hi95 = oc['cagr_d'] - 1.96 * se, oc['cagr_d'] + 1.96 * se
top = SENS[0]
for k, v in (('Standard error, 10-yr CAGR', f'±{se:.2f} pts'),
             ('95% band, optimized', f'{MINUS if lo95 < 0 else ""}{hu(abs(lo95), 1)} to {hu(hi95, 1)}%'),
             ('Chance the baseline out-returns', f'{hu(CALB["p"] * 100, 0)}%'),
             ('Allocations separable in 10 yrs', f'{SEP} of {SEP_N}'),
             (f'Most sensitive: {top["label"]}', f'1 pt → {sgn(top["d_cagr"])} CAGR'),
             ('On J.P. Morgan&#8217;s return inputs', f'{JPM["rows"]["baseline"]["cagr"]:.2f}% vs {JPM["rows"]["optimized"]["cagr"]:.2f}%')):
    present(f'confidence: {k}', f'<span class="k">{k}</span><span class="v">{v}</span>', P)
Hh = M.INSTITUTIONAL
for n_, d_ in Hh.items():
    present(f'house row {n_}', f'<tr><td>{n_}</td><td class="n">{d_["us"]:.1f}%</td><td class="n">{d_["em"]:.1f}%</td></tr>', P)
present('this page against the houses', f'<tr class="hl"><td>This page</td><td class="n">{q["gross"]:.2f}%</td><td class="n">{i["gross"]:.2f}%</td></tr>', P)
present('US margin over the houses', f'{hu(q["gross"] - max(d_["us"] for d_ in Hh.values()), 1)} points above the highest house', P)
present('houses ranking EM first', f'{sum(d_["em"] > d_["us"] for d_ in Hh.values())} of {len(Hh)} houses rank EM above the US', P)
_jv = Hh[M.ALT_SOURCE]['em_vol']; _lo, _hi = M.REGIME['calm']['vol']['IEMG'], M.REGIME['normalized']['vol']['IEMG']
present('J.P. Morgan EM volatility against the regimes',
        f'{_jv}% EM volatility sits {"between" if _lo <= _jv <= _hi else "above both of" if _jv > _hi else "below both of"} this page&#8217;s two regimes ({_lo:.1f}%, {_hi:.1f}%)', P)
present('policy driver date and vote', f'The Fed hiked 12–0 on {day(M.FOMC_DATE)}', pane('p-macro'))
ck('the most sensitive input is QQQ earnings growth', top['label'] == 'QQQ earnings growth', top['label'])
present('still open: the three assumptions', f'QQQ&#8217;s {q["eps"]:.1f}%/yr earnings growth (the most load-bearing), the {M.DD_MULT:.2f} × σ drawdown rule, '
        f'and BMNR&#8217;s {M.BMNR["eth"]:.0f}%/yr ETH return', P)
present('rationale: horizon', f'SGOV turns $10,000 into ${E["sleeves"]["SGOV"]["terminal"]:,}, QQQ into ${E["sleeves"]["QQQ"]["terminal"]:,}', P)
present('rationale: tilt', f'per unit of risk it is {rel} QQQ ({rv["IEMG"]:.3f} vs {rv["QQQ"]:.3f}) while earning '
        f'{"less" if i["net"] < q["net"] else "more"} ({i["net"]:.2f}% vs {q["net"]:.2f}%)', P)
present('rationale: sizing', f'The weights are set against {neg(on["dd"])}% drawdown, not today&#8217;s {neg(oc["dd"])}%', P)
present('rationale: CAL ratio', f'holds return-per-drawdown at {cal[0]:.4f} whatever the cash weight', P)
present('rationale: BMNR', f'{on["rc"]["BMNR"]:.1f}% of risk from {O["BMNR"]}% of capital', P)
present('rationale: overruled book', f'QQQ {BEST["QQQ"]} / IEMG {BEST["IEMG"]} / SGOV {BEST["SGOV"]} / BMNR {BEST["BMNR"]} '
        f'(Sharpe {M.stats(BEST, "calm")["sharpe"]:.3f} vs {oc["sharpe"]:.3f}), holds a {BEST["SGOV"]}% reserve', P)
present('recommendation', f'Hold QQQ {O["QQQ"]} / IEMG {O["IEMG"]} / SGOV {O["SGOV"]} / BMNR {O["BMNR"]}: {neg(on["dd"])}% normalized drawdown '
        f'against the baseline&#8217;s {neg(bn["dd"])}%, for {gap:.2f} points of CAGR', P)
present('recommendation: VIX trigger distance', f'Revisit if the VIX holds above {M.VIX_MEAN} ({hu(M.VIX_MEAN - SPOT)} points away', P)
mut = open('mutate.py').read()
# counted separately and summed, NOT with build.py's pattern: sharing one regex let
# both files agree on 62 while mutate.py ran 83
n_mut = mut.count('\n ("') + mut.count('\n G(')
ck('mutation tables are non-trivial', mut.count('\n ("') > 40 and mut.count('\n G(') > 15, n_mut)
present('mutation count matches mutate.py', f'{n_mut} deliberate corruptions of the model and the generator were all caught', P)
n_corr = int(re.search(r'CORRECTIONS: (\d+)', open('VERIFICATION.md').read()).group(1))
present('correction count matches VERIFICATION.md', f'{n_corr} corrections recorded', P)
ck('VERIFICATION.md lists the current revision', f'## Rev. {M.REVISION} ' in open('VERIFICATION.md').read(), M.REVISION)
present('disclaimer: sensitivity', f'moves the recommended book&#8217;s CAGR by {hu(abs(top["d_cagr"]))} and the gap between the books by {hu(abs(top["d_gap"]), 3)}', P)
present('disclaimer: data dates', f'Market data to the {day(MK["asof"], False)} close; fund prices as dated on each slide; '
        f'BMNR holdings from its {day(H["asof"], False)} release', P)
for dom_ in ('www.federalreserve.gov', 'www.bls.gov', 'www.ecb.europa.eu', 'www.imf.org', 'fred.stlouisfed.org',
             'www.sec.gov', 'www.ishares.com', 'www.invesco.com', 'www.cboe.com'):
    present(f'source cited: {dom_}', f'href="https://{dom_}/', P)

# ══ 7 · hygiene ═══════════════════════════════════════════════════════════════
vis = re.sub(r'<style>.*?</style>|<svg.*?</svg>|<script>.*?</script>|<[^>]+>', ' ', html, flags=re.S)
ascii_minus = re.findall(r'(?<![\w/–-])-\d[\d.]*%', vis)
ck('no ASCII hyphen on a signed figure', not ascii_minus, ascii_minus[:5], 'none')
# Superseded values, anchored to the markup they lived in. The meta-check compares
# the figures INSIDE each entry with every figure the model now emits, so an entry
# that has become correct again fails loudly instead of failing a correct page.
STALE = (('VIX 15.35', 'pre-settlement VIX snapshot, 23 Sep'), ('<b>14.25</b>', 'wrong 22 Sep VIX close'),
         ('4.93%', 'wrong 22 Sep 10-year close'), ('(28 August)', 'misdated 2026 VIX low'),
         ('Market data is as of 11 September', 'stale disclaimer date'), ('0.1055', 'superseded CAL ratio'))
for s_, why in STALE:
    ck(f'no superseded value ({why})', s_ not in html, s_, 'absent')
live = {f'{v:.2f}' for v in vals} | {f'{MK[k]:.2f}' for k in ('brent', 'ust10', 'ust10_prev', 'brent_prev')} | {f'{cal[0]:.4f}'}
for p in M.PORTFOLIOS:
    for r in M.REGIME:
        s_ = ST[p][r]; live |= {f"{s_['vol']:.2f}", f"{s_['dd']:.1f}", f"{s_['cagr_d']:.2f}"} | {f'{x:.1f}' for x in s_['rc'].values()}
tok = lambda t: set(re.findall(r'\d+\.\d+', t))
ck('no blacklist entry collides with a live figure', not [s_ for s_, _ in STALE if tok(s_) & live], [s_ for s_, _ in STALE if tok(s_) & live])

print(f'{checks} checks, {len(fails)} failed')
for f_ in fails: print('  FAIL', f_)
sys.exit(1 if fails else 0)
